// Diccionario de traducciones de tratamientos dentales
// ES → EN → FR
// Generado manualmente — sin necesidad de API externa

export const TREATMENT_DICT = {
  "1 gramo de hueso": { en: "1 gram of bone graft", fr: "1 gramme de greffe osseuse" },
  "2 gramos de hueso": { en: "2 grams of bone graft", fr: "2 grammes de greffe osseuse" },
  "24 Control Ortodoncia externa": { en: "24 External Orthodontic Check-up", fr: "24 Contrôle Orthodontie externe" },
  "3 gramos de hueso": { en: "3 grams of bone graft", fr: "3 grammes de greffe osseuse" },
  "3er": { en: "3rd", fr: "3ème" },
  "4 IMPLANTES + BARRA ACKERMAN +SOBREDENTADURA METAL ACRILICA REMOVIBLE + EXOS + PROTESIS PROVISIONAL": { en: "4 IMPLANTS + ACKERMAN BAR + REMOVABLE METAL ACRYLIC OVERDENTURE + ABUTMENTS + PROVISIONAL PROSTHESIS", fr: "4 IMPLANTS + BARRE ACKERMAN + OVERDENTURE MÉTALLIQUE ACRYLIQUE AMOVIBLE + PILIERS + PROTHÈSE PROVISOIRE" },
  "6 IMPLANTES + ARCADA CERAMICA 12 PIEZAS INFERIOR": { en: "6 IMPLANTS + CERAMIC ARCH 12 UNITS LOWER", fr: "6 IMPLANTS + ARCADE CÉRAMIQUE 12 UNITÉS INFÉRIEURE" },
  "6 IMPLANTES + ARCADA CERAMICA 12 PIEZAS SUPERIOR": { en: "6 IMPLANTS + CERAMIC ARCH 12 UNITS UPPER", fr: "6 IMPLANTS + ARCADE CÉRAMIQUE 12 UNITÉS SUPÉRIEURE" },
  "6 IMPLANTES + PROTESIS HIBRIDA  INFERIOR": { en: "6 IMPLANTS + HYBRID PROSTHESIS LOWER", fr: "6 IMPLANTS + PROTHÈSE HYBRIDE INFÉRIEURE" },
  "6 IMPLANTES + PROTESIS HIBRIDA SUPERIOR": { en: "6 IMPLANTS + HYBRID PROSTHESIS UPPER", fr: "6 IMPLANTS + PROTHÈSE HYBRIDE SUPÉRIEURE" },
  "8 IMPLANTES + ARCADA CERAMICA (14)+ EXOS + PROT. PROV. INFERIOR": { en: "8 IMPLANTS + CERAMIC ARCH (14) + ABUTMENTS + PROV. PROSTH. LOWER", fr: "8 IMPLANTS + ARCADE CÉRAMIQUE (14) + PILIERS + PROTH. PROV. INFÉRIEURE" },
  "8 IMPLANTES + ARCADA CERAMICA (14)+ EXOS + PROT. PROV. SUPERIOR": { en: "8 IMPLANTS + CERAMIC ARCH (14) + ABUTMENTS + PROV. PROSTH. UPPER", fr: "8 IMPLANTS + ARCADE CÉRAMIQUE (14) + PILIERS + PROTH. PROV. SUPÉRIEURE" },
  "ACIDO HIALURONICO": { en: "HYALURONIC ACID", fr: "ACIDE HYALURONIQUE" },
  "ADITAMENTOS IMPLANTE EXTERNO": { en: "EXTERNAL IMPLANT ABUTMENTS", fr: "PILIERS IMPLANT EXTERNE" },
  "AJUSTE OCLUSAL": { en: "OCCLUSAL ADJUSTMENT", fr: "AJUSTEMENT OCCLUSAL" },
  "AJUSTE PROTESIS SOBRE IMPLANTES": { en: "IMPLANT-SUPPORTED PROSTHESIS ADJUSTMENT", fr: "AJUSTEMENT PROTHÈSE SUR IMPLANTS" },
  "Apicoformació (per sessió)": { en: "Apexification (per session)", fr: "Apexification (par séance)" },
  "ARCADA CERAMICA DEFINITIVA (INCL. ADITAMENTOS)": { en: "DEFINITIVE CERAMIC ARCH (INCL. ABUTMENTS)", fr: "ARCADE CÉRAMIQUE DÉFINITIVE (INCL. PILIERS)" },
  "Arcada cerámica sobre implantes (12) inferior": { en: "Ceramic arch on implants (12) lower", fr: "Arcade céramique sur implants (12) inférieure" },
  "Arcada cerámica sobre implantes (12) superior": { en: "Ceramic arch on implants (12) upper", fr: "Arcade céramique sur implants (12) supérieure" },
  "Arcada cerámica sobre implantes (14) inferior": { en: "Ceramic arch on implants (14) lower", fr: "Arcade céramique sur implants (14) inférieure" },
  "Arcada cerámica sobre implantes (14) superior": { en: "Ceramic arch on implants (14) upper", fr: "Arcade céramique sur implants (14) supérieure" },
  "ARCADA CON IMPLANTES ZIGOMATICOS": { en: "ARCH WITH ZYGOMATIC IMPLANTS", fr: "ARCADE AVEC IMPLANTS ZYGOMATIQUES" },
  "Atache para prótesis removible": { en: "Attachment for removable prosthesis", fr: "Attachement pour prothèse amovible" },
  "Ataches (unidad)": { en: "Attachments (unit)", fr: "Attachements (unité)" },
  "Ataches + Sobredentadura Acrílica Inferior": { en: "Attachments + Lower Acrylic Overdenture", fr: "Attachements + Overdenture Acrylique Inférieure" },
  "Ataches + Sobredentadura metal acrílica superior": { en: "Attachments + Upper Metal Acrylic Overdenture", fr: "Attachements + Overdenture Métallique Acrylique Supérieure" },
  "Barra Ackerman con sobredentadura removible inferior": { en: "Ackerman bar with lower removable overdenture", fr: "Barre Ackerman avec overdenture amovible inférieure" },
  "Barra Ackerman con sobredentadura removible superior": { en: "Ackerman bar with upper removable overdenture", fr: "Barre Ackerman avec overdenture amovible supérieure" },
  "Blanqueamento interno": { en: "Internal bleaching", fr: "Blanchiment interne" },
  "Blanqueamiento dental ambulatorio (férulas + Kit 2 jeringas)": { en: "Home dental bleaching (trays + 2-syringe kit)", fr: "Blanchiment dentaire ambulatoire (gouttières + kit 2 seringues)" },
  "Blanqueamiento dental en consulta (por arcada)": { en: "In-office dental bleaching (per arch)", fr: "Blanchiment dentaire en cabinet (par arcade)" },
  "Blanqueamiento dental por pieza": { en: "Dental bleaching per tooth", fr: "Blanchiment dentaire par dent" },
  "Blanqueamiento OPALESCENCE GO 16%": { en: "OPALESCENCE GO 16% bleaching", fr: "Blanchiment OPALESCENCE GO 16%" },
  "Blanqueamiento Promo 2 arcadas": { en: "Bleaching promo 2 arches", fr: "Blanchiment promo 2 arcades" },
  "Botón de Nance superior": { en: "Upper Nance button", fr: "Bouton de Nance supérieur" },
  "Cambio de dientes a prótesis híbrida": { en: "Teeth replacement to hybrid prosthesis", fr: "Remplacement des dents pour prothèse hybride" },
  "CAMBIO DIENTES PROTESIS REMOVIBLE": { en: "REMOVABLE PROSTHESIS TEETH REPLACEMENT", fr: "REMPLACEMENT DENTS PROTHÈSE AMOVIBLE" },
  "Cambio Tornillo Corona sobre Implante": { en: "Implant crown screw replacement", fr: "Remplacement vis couronne sur implant" },
  "Carilla ceràmica": { en: "Ceramic veneer", fr: "Facette céramique" },
  "Carilla de Composite": { en: "Composite veneer", fr: "Facette composite" },
  "Carilla Disilicato Ceràmica x tècniques de capa": { en: "Ceramic disilicate veneer (layering technique)", fr: "Facette céramique disilicate (technique de stratification)" },
  "Carilla provisional": { en: "Provisional veneer", fr: "Facette provisoire" },
  "Cementar piercing": { en: "Dental piercing cementation", fr: "Cimentation piercing dentaire" },
  "Cirugia 3er Molar con Cirujano (ex-od-ost-colgajo)": { en: "3rd Molar Surgery with Surgeon (ext-odont-osteot-flap)", fr: "Chirurgie 3ème Molaire avec Chirurgien (ext-odont-ostéot-lambeau)" },
  "Cirugía periodontal arcada inferior": { en: "Periodontal surgery lower arch", fr: "Chirurgie parodontale arcade inférieure" },
  "Cirugía Periodontal arcada superior": { en: "Periodontal surgery upper arch", fr: "Chirurgie parodontale arcade supérieure" },
  "Colgajo": { en: "Flap surgery", fr: "Lambeau chirurgical" },
  "Complemento braquets autoligables": { en: "Self-ligating brackets supplement", fr: "Complément brackets auto-ligaturants" },
  "Compostura": { en: "Repair", fr: "Réparation" },
  "Compostura de porcelana": { en: "Porcelain repair", fr: "Réparation en porcelaine" },
  "Compostura más refuerzo metálico": { en: "Repair with metal reinforcement", fr: "Réparation avec renfort métallique" },
  "Compostura mat.especial o agregar malla metálica": { en: "Special material repair or metal mesh addition", fr: "Réparation matériau spécial ou ajout grille métallique" },
  "COMPOSTURA PROTESIS": { en: "PROSTHESIS REPAIR", fr: "RÉPARATION PROTHÈSE" },
  "Compostura Simple de Resina": { en: "Simple resin repair", fr: "Réparation simple en résine" },
  "Compostura y Agregado de pieza (unidad)": { en: "Repair and tooth addition (unit)", fr: "Réparation et ajout de dent (unité)" },
  "Control Anual + OPG + Tartrectomía ambas arcadas": { en: "Annual check-up + OPG + Scaling both arches", fr: "Contrôle annuel + OPG + Détartrage deux arcades" },
  "Control mensual Ortodoncia": { en: "Monthly orthodontic check-up", fr: "Contrôle mensuel Orthodontie" },
  "Control Ortodoncia": { en: "Orthodontic check-up", fr: "Contrôle Orthodontie" },
  "Control Ortodoncia externa": { en: "External orthodontic check-up", fr: "Contrôle Orthodontie externe" },
  "Corona de disilicato de Litio": { en: "Lithium disilicate crown", fr: "Couronne en disilicate de lithium" },
  "Corona metal ceramica": { en: "Metal-ceramic crown", fr: "Couronne métal-céramique" },
  "Corona metal cerámica sobre implante": { en: "Metal-ceramic crown on implant", fr: "Couronne métal-céramique sur implant" },
  "Corona o puente metal - cerámica": { en: "Metal-ceramic crown or bridge", fr: "Couronne ou bridge métal-céramique" },
  "Corona o puente zirconio": { en: "Zirconia crown or bridge", fr: "Couronne ou bridge zircone" },
  "CORONA PROVISIONAL": { en: "PROVISIONAL CROWN", fr: "COURONNE PROVISOIRE" },
  "Corona provisional sobre implante inmediato": { en: "Provisional crown on immediate implant", fr: "Couronne provisoire sur implant immédiat" },
  "Corona sobre implante promoción": { en: "Implant crown promotion", fr: "Couronne sur implant promotion" },
  "Corona zirconio": { en: "Zirconia crown", fr: "Couronne zircone" },
  "Corona zirconio sobre implante": { en: "Zirconia crown on implant", fr: "Couronne zircone sur implant" },
  "CORTAR PUENTE": { en: "BRIDGE SECTIONING", fr: "SECTION DE BRIDGE" },
  "CURETAJE - Mantenimiento con retirada de prótesis sobre implantes inferior": { en: "CURETTAGE - Maintenance with removal of lower implant prosthesis", fr: "CURETAGE - Maintenance avec retrait prothèse implants inférieure" },
  "CURETAJE - Mantenimiento con retirada de prótesis sobre implantes superior": { en: "CURETTAGE - Maintenance with removal of upper implant prosthesis", fr: "CURETAGE - Maintenance avec retrait prothèse implants supérieure" },
  "Curetaje arcada inferior": { en: "Curettage lower arch", fr: "Curetage arcade inférieure" },
  "Curetaje arcada superior": { en: "Curettage upper arch", fr: "Curetage arcade supérieure" },
  "Curetaje con retirada de ortodoncia externa": { en: "Curettage with removal of external orthodontics", fr: "Curetage avec retrait orthodontie externe" },
  "Curetaje con retirada de ortodoncia externa superior e inferior": { en: "Curettage with removal of upper and lower external orthodontics", fr: "Curetage avec retrait orthodontie externe supérieure et inférieure" },
  "Curetaje general": { en: "General curettage", fr: "Curetage général" },
  "Desmontaje mecanico puente": { en: "Mechanical bridge removal", fr: "Démontage mécanique bridge" },
  "DESMONTAJE PROTESIS SOBRE IMPLANTES": { en: "IMPLANT PROSTHESIS REMOVAL", fr: "DÉMONTAGE PROTHÈSE SUR IMPLANTS" },
  "Diente provisional": { en: "Provisional tooth", fr: "Dent provisoire" },
  "Elevación de Seno Bilateral": { en: "Bilateral sinus lift", fr: "Élévation sinusienne bilatérale" },
  "Elevación de Seno interna": { en: "Internal sinus lift", fr: "Élévation sinusienne interne" },
  "Empaste Simple": { en: "Simple filling", fr: "Obturation simple" },
  "Endodoncia (1-2-3)": { en: "Root canal treatment (1-2-3 canals)", fr: "Traitement endodontique (1-2-3 canaux)" },
  "Endodoncia (4-5)": { en: "Root canal treatment (4-5 canals)", fr: "Traitement endodontique (4-5 canaux)" },
  "Endodoncia (6-7)": { en: "Root canal treatment (6-7 canals)", fr: "Traitement endodontique (6-7 canaux)" },
  "Endodoncias (1-2-3)": { en: "Root canal treatments (1-2-3 canals)", fr: "Traitements endodontiques (1-2-3 canaux)" },
  "Estudio Invisaling": { en: "Invisalign study", fr: "Étude Invisalign" },
  "Exodoncia 3er Molar retenido": { en: "Impacted 3rd molar extraction", fr: "Extraction 3ème molaire incluse" },
  "Exodoncia 3er Molar semiretenido + colgajo": { en: "Semi-impacted 3rd molar extraction + flap", fr: "Extraction 3ème molaire semi-incluse + lambeau" },
  "Exodoncia 3er Molar simple": { en: "Simple 3rd molar extraction", fr: "Extraction simple 3ème molaire" },
  "EXODONCIA 3º MOLAR + COLGAJO+ODONTOSECCION": { en: "3RD MOLAR EXTRACTION + FLAP + ODONTOSECTION", fr: "EXTRACTION 3ÈME MOLAIRE + LAMBEAU + ODONTOSECTION" },
  "EXODONCIA 3r MOLAR RESTO RADICULAR": { en: "3RD MOLAR ROOT REMNANT EXTRACTION", fr: "EXTRACTION RESTE RADICULAIRE 3ÈME MOLAIRE" },
  "EXODONCIA CANINO RETENIDO": { en: "IMPACTED CANINE EXTRACTION", fr: "EXTRACTION CANINE INCLUSE" },
  "Exodoncia compleja - No 3r Molar -": { en: "Complex extraction - not 3rd molar -", fr: "Extraction complexe - pas 3ème molaire -" },
  "EXODONCIA COMPLEJA CON CIRUJANO": { en: "COMPLEX EXTRACTION WITH SURGEON", fr: "EXTRACTION COMPLEXE AVEC CHIRURGIEN" },
  "EXODONCIA CON QUISTECTOMIA": { en: "EXTRACTION WITH CYSTECTOMY", fr: "EXTRACTION AVEC KYSTECTOMIE" },
  "EXODONCIA DE URGENCIA": { en: "EMERGENCY EXTRACTION", fr: "EXTRACTION D'URGENCE" },
  "EXODONCIA DIENTE SUPERNUMERARIO": { en: "SUPERNUMERARY TOOTH EXTRACTION", fr: "EXTRACTION DENT SURNUMÉRAIRE" },
  "EXODONCIA DIENTE SUPERNUMERARIO CON ODONTOSECCION Y COLGAJO": { en: "SUPERNUMERARY TOOTH EXTRACTION WITH ODONTOSECTION AND FLAP", fr: "EXTRACTION DENT SURNUMÉRAIRE AVEC ODONTOSECTION ET LAMBEAU" },
  "EXODONCIA QUIRÚRGICA (MÚTUA)": { en: "SURGICAL EXTRACTION (INSURANCE)", fr: "EXTRACTION CHIRURGICALE (MUTUELLE)" },
  "Exodoncia resto radicular compleja": { en: "Complex root remnant extraction", fr: "Extraction reste radiculaire complexe" },
  "Exodoncia resto radicular simple": { en: "Simple root remnant extraction", fr: "Extraction reste radiculaire simple" },
  "Exodoncia simple": { en: "Simple extraction", fr: "Extraction simple" },
  "Extraccion de implante": { en: "Implant removal", fr: "Extraction d'implant" },
  "Extracción diente temporal": { en: "Deciduous tooth extraction", fr: "Extraction dent temporaire" },
  "Fenestración diente incluido": { en: "Fenestration of impacted tooth", fr: "Fenestration dent incluse" },
  "Férula blanda": { en: "Soft splint", fr: "Gouttière souple" },
  "Férula de descarga neuromiorrelajante (Michigan)": { en: "Michigan neuromuscular discharge splint", fr: "Gouttière de décharge neuromusculaire (Michigan)" },
  "Ferulización de dientes": { en: "Dental splinting", fr: "Contention dentaire" },
  "Fluorizaciones": { en: "Fluoride applications", fr: "Fluoration" },
  "Frenectomía": { en: "Frenectomy", fr: "Frénectomie" },
  "Gancho Estético flex": { en: "Aesthetic flex clasp", fr: "Crochet esthétique flex" },
  "Gingive": { en: "Gingiva", fr: "Gencive" },
  "Gingivectomía (alargamiento coronario por pieza)": { en: "Gingivectomy (crown lengthening per tooth)", fr: "Gingivectomie (allongement coronaire par dent)" },
  "GOMAS LOCATOR": { en: "LOCATOR RUBBER INSERTS", fr: "BAGUES LOCATOR" },
  "Gran Reconstrucción": { en: "Major reconstruction", fr: "Grande reconstruction" },
  "Hass Disyuntor": { en: "Haas expander", fr: "Disjoncteur de Haas" },
  "HIGIENE BUCODENTAL PROFUNDA": { en: "DEEP ORAL HYGIENE", fr: "HYGIÈNE BUCCO-DENTAIRE APPROFONDIE" },
  "HIGIENE DENTAL PROMO": { en: "DENTAL HYGIENE PROMO", fr: "PROMOTION HYGIÈNE DENTAIRE" },
  "IMPLANT DENTAIRE": { en: "DENTAL IMPLANT", fr: "IMPLANT DENTAIRE" },
  "Implante Alta Gama Exagono interno": { en: "High-end internal hexagon implant", fr: "Implant haute gamme hexagone interne" },
  "Implante Titanio": { en: "Titanium implant", fr: "Implant en titane" },
  "Implante titanio BioHorizons/Zimmer (alta gama)": { en: "BioHorizons/Zimmer titanium implant (high-end)", fr: "Implant titane BioHorizons/Zimmer (haute gamme)" },
  "Implante Titanio Zimmer Trabecular metal": { en: "Zimmer Trabecular metal titanium implant", fr: "Implant titane Zimmer métal trabéculaire" },
  "Incrustació IPF E.MAX Disilicato": { en: "IPF E.MAX disilicate inlay", fr: "Inlay IPF E.MAX disilicate" },
  "INCRUSTACION DE COMPOSITE": { en: "COMPOSITE INLAY", fr: "INLAY EN COMPOSITE" },
  "Incrustación IPF E.MAX Di Silicato Cerámica": { en: "IPF E.MAX ceramic disilicate inlay", fr: "Inlay céramique IPF E.MAX disilicate" },
  "Inicio": { en: "Start", fr: "Début" },
  "Injerto Gingival Libre": { en: "Free gingival graft", fr: "Greffe gingivale libre" },
  "Invisaling": { en: "Invisalign", fr: "Invisalign" },
  "IRRIGADOR BUCAL LACER HIDRO": { en: "LACER HYDRO ORAL IRRIGATOR", fr: "IRRIGATEUR BUCCAL LACER HYDRO" },
  "LIMPIEZA BUCAL DE MUTUA": { en: "INSURANCE ORAL CLEANING", fr: "NETTOYAGE BUCCAL MUTUELLE" },
  "Limpieza Bucodental + Fluorización": { en: "Oral cleaning + Fluoride treatment", fr: "Nettoyage bucco-dentaire + Fluoration" },
  "LIMPIEZA BUCODENTAL AMBAS ARCADAS DURANTE TRATAMIENTO ORTODONTICO": { en: "ORAL CLEANING BOTH ARCHES DURING ORTHODONTIC TREATMENT", fr: "NETTOYAGE BUCCO-DENTAIRE DEUX ARCADES PENDANT TRAITEMENT ORTHODONTIQUE" },
  "LIMPIEZA BUCODENTAL AMBAS ARCADAS SIN COSTE": { en: "ORAL CLEANING BOTH ARCHES AT NO COST", fr: "NETTOYAGE BUCCO-DENTAIRE DEUX ARCADES SANS FRAIS" },
  "Limpieza bucodental. Tartrectomía (ambas arcadas)": { en: "Oral cleaning. Scaling (both arches)", fr: "Nettoyage bucco-dentaire. Détartrage (deux arcades)" },
  "LIMPIEZA PROTESIS HIBRIDA": { en: "HYBRID PROSTHESIS CLEANING", fr: "NETTOYAGE PROTHÈSE HYBRIDE" },
  "Mantenedor de espacio": { en: "Space maintainer", fr: "Mainteneur d'espace" },
  "Mantenimiento": { en: "Maintenance", fr: "Maintenance" },
  "Mantenimiento de carillas de compo. Incl. Limpieza": { en: "Composite veneer maintenance incl. cleaning", fr: "Maintenance facettes composite incl. nettoyage" },
  "MANTENIMIENTO DE IMPLANTE": { en: "IMPLANT MAINTENANCE", fr: "MAINTENANCE IMPLANT" },
  "MANTENIMIENTO PERIODONTAL 4-6-8-ANUAL": { en: "PERIODONTAL MAINTENANCE 4-6-8-ANNUAL", fr: "MAINTENANCE PARODONTALE 4-6-8-ANNUEL" },
  "MANTENIMIENTO PERIODONTAL INFERIOR (3 MESES)": { en: "LOWER PERIODONTAL MAINTENANCE (3 MONTHS)", fr: "MAINTENANCE PARODONTALE INFÉRIEURE (3 MOIS)" },
  "MANTENIMIENTO PERIODONTAL INFERIOR (6 MESES)": { en: "LOWER PERIODONTAL MAINTENANCE (6 MONTHS)", fr: "MAINTENANCE PARODONTALE INFÉRIEURE (6 MOIS)" },
  "MANTENIMIENTO PERIODONTAL SUPERIOR (3 MESES)": { en: "UPPER PERIODONTAL MAINTENANCE (3 MONTHS)", fr: "MAINTENANCE PARODONTALE SUPÉRIEURE (3 MOIS)" },
  "MANTENIMIENTO PERIODONTAL SUPERIOR (6 MESES)": { en: "UPPER PERIODONTAL MAINTENANCE (6 MONTHS)", fr: "MAINTENANCE PARODONTALE SUPÉRIEURE (6 MOIS)" },
  "Mascara Facial": { en: "Facial mask (orthodontic)", fr: "Masque facial (orthodontique)" },
  "Membrana 15x20": { en: "Membrane 15x20", fr: "Membrane 15x20" },
  "Membrana 20X30": { en: "Membrane 20x30", fr: "Membrane 20x30" },
  "MEMBRANA TISULAR": { en: "TISSUE MEMBRANE", fr: "MEMBRANE TISSULAIRE" },
  "Mensualidades Fuerzas ortopédicas": { en: "Orthopedic forces monthly installments", fr: "Mensualités forces orthopédiques" },
  "Mensualidades ortodoncia ortopédica": { en: "Orthopedic orthodontics monthly installments", fr: "Mensualités orthodontie orthopédique" },
  "MICROTORNILLO ORTODONCIA": { en: "ORTHODONTIC MICRO-SCREW", fr: "MICRO-VIS ORTHODONTIQUE" },
  "Odontosección": { en: "Odontosection", fr: "Odontosection" },
  "OPERCULECTOMIA": { en: "OPERCULECTOMY", fr: "OPERCULECTOMIE" },
  "OPG. Ortopantomografía Panorámica Dental": { en: "OPG. Dental Panoramic Radiograph", fr: "OPG. Orthopantomographie Panoramique Dentaire" },
  "Pack": { en: "Package", fr: "Pack" },
  "PACK ORTODONCIA METALICA -12 CONTROLES + BLANQUEAMIENTO": { en: "METAL ORTHODONTICS PACK - 12 CHECK-UPS + BLEACHING", fr: "PACK ORTHODONTIE MÉTALLIQUE - 12 CONTRÔLES + BLANCHIMENT" },
  "PACK PROMO Rev+Rad+CURETAGE+BLANQUEAMIENTO": { en: "PROMO PACK Check-up+X-ray+CURETTAGE+BLEACHING", fr: "PACK PROMO Contrôle+Radio+CURETAGE+BLANCHIMENT" },
  "Pack Retenedores Invisaling Vivera 2 arcadas": { en: "Invisalign Vivera retainers pack 2 arches", fr: "Pack contentions Invisalign Vivera 2 arcades" },
  "Pack Tratamiento ortodoncia brackets metálicos 12 visitas": { en: "Metal brackets orthodontic treatment pack 12 visits", fr: "Pack traitement orthodontique brackets métalliques 12 visites" },
  "Pack Tratamiento ortodoncia brackets metálicos 18 visitas": { en: "Metal brackets orthodontic treatment pack 18 visits", fr: "Pack traitement orthodontique brackets métalliques 18 visites" },
  "Pack Tratamiento ortodoncia brackets metálicos 24 visitas": { en: "Metal brackets orthodontic treatment pack 24 visits", fr: "Pack traitement orthodontique brackets métalliques 24 visites" },
  "Parcial Flexible Partial Flex mas de 3 piezas inf.": { en: "Flexible partial denture more than 3 units lower", fr: "Prothèse partielle flexible plus de 3 unités inférieure" },
  "Perno": { en: "Post", fr: "Tenon" },
  "Perno Colado Indirecto": { en: "Indirect cast post", fr: "Tenon coulé indirect" },
  "Perno Fibra de Vidrio": { en: "Fiberglass post", fr: "Tenon en fibre de verre" },
  "Perno Pasante": { en: "Through post", fr: "Tenon transfixant" },
  "Piercing dental": { en: "Dental piercing", fr: "Piercing dentaire" },
  "Pilar transepitelial titanio (unidad)": { en: "Titanium transepithelial abutment (unit)", fr: "Pilier transépithélial titane (unité)" },
  "Placa Expansiva": { en: "Expansion plate", fr: "Plaque expansive" },
  "Placa Sanders": { en: "Sanders plate", fr: "Plaque de Sanders" },
  "Protección pulpar": { en: "Pulp protection", fr: "Protection pulpaire" },
  "Prótesis": { en: "Prosthesis", fr: "Prothèse" },
  "Protesis Completa acrílic inferior DEFINITIVA": { en: "Complete lower acrylic denture DEFINITIVE", fr: "Prothèse complète acrylique inférieure DÉFINITIVE" },
  "Protesis Completa acrílic provisional inferior": { en: "Complete lower acrylic denture provisional", fr: "Prothèse complète acrylique inférieure provisoire" },
  "Protesis Completa Acrílic provisional superior": { en: "Complete upper acrylic denture provisional", fr: "Prothèse complète acrylique supérieure provisoire" },
  "Protesis Completa acrílic superior DEFINITIVA": { en: "Complete upper acrylic denture DEFINITIVE", fr: "Prothèse complète acrylique supérieure DÉFINITIVE" },
  "PROTESIS COMPLETA FLEXIBLE": { en: "COMPLETE FLEXIBLE DENTURE", fr: "PROTHÈSE COMPLÈTE FLEXIBLE" },
  "Prótesis Híbrida de Metal Noble (titanio) inferior": { en: "Lower noble metal (titanium) hybrid prosthesis", fr: "Prothèse hybride métal noble (titane) inférieure" },
  "Prótesis Híbrida de Metal Noble (titanio) superior": { en: "Upper noble metal (titanium) hybrid prosthesis", fr: "Prothèse hybride métal noble (titane) supérieure" },
  "PROTESIS INMEDIATA SOBRE IMPLANTES": { en: "IMMEDIATE IMPLANT-SUPPORTED PROSTHESIS", fr: "PROTHÈSE IMMÉDIATE SUR IMPLANTS" },
  "PROTESIS MIXTA CON ATACHES DE 4 A 6 PZ": { en: "MIXED PROSTHESIS WITH ATTACHMENTS 4 TO 6 UNITS", fr: "PROTHÈSE MIXTE AVEC ATTACHEMENTS 4 À 6 UNITÉS" },
  "PROTESIS MIXTA CON ATACHES DE 7 A 9 PZ": { en: "MIXED PROSTHESIS WITH ATTACHMENTS 7 TO 9 UNITS", fr: "PROTHÈSE MIXTE AVEC ATTACHEMENTS 7 À 9 UNITÉS" },
  "Protesis Parcial acrilica 1 a 3 piezas superior": { en: "Upper acrylic partial denture 1 to 3 units", fr: "Prothèse partielle acrylique supérieure 1 à 3 unités" },
  "Protesis Parcial acrílica de 1 a 3 piezas inferior": { en: "Lower acrylic partial denture 1 to 3 units", fr: "Prothèse partielle acrylique inférieure 1 à 3 unités" },
  "Protesis Parcial acrilica de 4 a 6 piezas inferior": { en: "Lower acrylic partial denture 4 to 6 units", fr: "Prothèse partielle acrylique inférieure 4 à 6 unités" },
  "Protesis Parcial acrílica de 4 a 6 piezas superior": { en: "Upper acrylic partial denture 4 to 6 units", fr: "Prothèse partielle acrylique supérieure 4 à 6 unités" },
  "Protesis Parcial acrilica mas de 7 piezas inferior": { en: "Lower acrylic partial denture more than 7 units", fr: "Prothèse partielle acrylique inférieure plus de 7 unités" },
  "Protesis Parcial acrilica mas de 7 piezas superior": { en: "Upper acrylic partial denture more than 7 units", fr: "Prothèse partielle acrylique supérieure plus de 7 unités" },
  "Protesis Parcial Esqueletica 1 a 3 piezas inferior": { en: "Lower skeletal partial denture 1 to 3 units", fr: "Prothèse partielle squelettique inférieure 1 à 3 unités" },
  "Protesis Parcial Esqueletica 1 a 3 piezas superior": { en: "Upper skeletal partial denture 1 to 3 units", fr: "Prothèse partielle squelettique supérieure 1 à 3 unités" },
  "Protesis Parcial Esqueletica 4 a 6 piezas inferior": { en: "Lower skeletal partial denture 4 to 6 units", fr: "Prothèse partielle squelettique inférieure 4 à 6 unités" },
  "Protesis Parcial Esqueletica 4 a 6 piezas superior": { en: "Upper skeletal partial denture 4 to 6 units", fr: "Prothèse partielle squelettique supérieure 4 à 6 unités" },
  "Protesis Parcial Esqueletica 7 a 9 piezas inferior": { en: "Lower skeletal partial denture 7 to 9 units", fr: "Prothèse partielle squelettique inférieure 7 à 9 unités" },
  "Protesis Parcial Esqueletica 7 a 9 piezas superior": { en: "Upper skeletal partial denture 7 to 9 units", fr: "Prothèse partielle squelettique supérieure 7 à 9 unités" },
  "Protesis Parcial Esqueletica mas de 10 piezas inf.": { en: "Lower skeletal partial denture more than 10 units", fr: "Prothèse partielle squelettique inférieure plus de 10 unités" },
  "Protesis Parcial Esqueletica mas de 10 piezas sup.": { en: "Upper skeletal partial denture more than 10 units", fr: "Prothèse partielle squelettique supérieure plus de 10 unités" },
  "PROTHÈSE DENTAIRE COMPLÈTE TRANSVISSÉE IMPLANTOPORTÉE": { en: "COMPLETE SCREW-RETAINED IMPLANT-SUPPORTED PROSTHESIS", fr: "PROTHÈSE DENTAIRE COMPLÈTE TRANSVISSÉE IMPLANTOPORTÉE" },
  "Puente Maryland metal - resina": { en: "Maryland bridge metal-resin", fr: "Bridge Maryland métal-résine" },
  "Puente Maryland metal- ceramica (una pieza)": { en: "Maryland bridge metal-ceramic (one unit)", fr: "Bridge Maryland métal-céramique (une unité)" },
  "Puente Maryland resina a partir de una pieza": { en: "Maryland resin bridge from one unit", fr: "Bridge Maryland résine à partir d'une unité" },
  "Pulido de carillas (unidad)": { en: "Veneer polishing (unit)", fr: "Polissage facettes (unité)" },
  "Pulpotomia": { en: "Pulpotomy", fr: "Pulpotomie" },
  "Quad Helix superior": { en: "Upper quad helix", fr: "Quad hélix supérieur" },
  "Quistectomías maxilares": { en: "Jaw cystectomies", fr: "Kystectomies maxillaires" },
  "Rebase": { en: "Denture relining", fr: "Rebasage prothèse" },
  "Rebase corriente": { en: "Standard relining", fr: "Rebasage standard" },
  "Rebase en el 1er año prót. removible nueva": { en: "Relining in 1st year new removable prosthesis", fr: "Rebasage 1ère année nouvelle prothèse amovible" },
  "Rebase resina blanda en clínica": { en: "Soft resin relining in clinic", fr: "Rebasage résine souple en cabinet" },
  "Rebase resina en laboratorio": { en: "Resin relining in laboratory", fr: "Rebasage résine en laboratoire" },
  "Recementado de Corona por pieza": { en: "Crown recementation per unit", fr: "Recimentation couronne par unité" },
  "Recementado de mantenedor": { en: "Space maintainer recementation", fr: "Recimentation mainteneur d'espace" },
  "Recementado Incrustación": { en: "Inlay recementation", fr: "Recimentation inlay" },
  "Reconstrucción": { en: "Reconstruction", fr: "Reconstruction" },
  "Reconstrucción angular estética": { en: "Aesthetic angular reconstruction", fr: "Reconstruction angulaire esthétique" },
  "Reconstrucción pieza endodonciada": { en: "Endodontically treated tooth reconstruction", fr: "Reconstruction dent dépulpée" },
  "Reconstrucción posible endodoncia": { en: "Reconstruction possible endodontics", fr: "Reconstruction possible endodontie" },
  "Reendodoncia (1-2-3)": { en: "Root canal retreatment (1-2-3 canals)", fr: "Retraitement endodontique (1-2-3 canaux)" },
  "Reendodoncia (4-5)": { en: "Root canal retreatment (4-5 canals)", fr: "Retraitement endodontique (4-5 canaux)" },
  "Reendodoncia (6-7)": { en: "Root canal retreatment (6-7 canals)", fr: "Retraitement endodontique (6-7 canaux)" },
  "Regularización del revorde dental alveolar": { en: "Alveolar ridge regularisation", fr: "Régularisation de la crête alvéolaire" },
  "Reimplante": { en: "Reimplantation", fr: "Réimplantation" },
  "Reinicio de Ortodoncia (Braquets autoligables)": { en: "Orthodontic restart (self-ligating brackets)", fr: "Reprise Orthodontie (brackets auto-ligaturants)" },
  "Renovación de Retenedor(sup/inf) fuera de garantia": { en: "Retainer renewal (upper/lower) out of warranty", fr: "Renouvellement contention (sup/inf) hors garantie" },
  "REPARACIÓN BARRA ACKERMAN": { en: "ACKERMAN BAR REPAIR", fr: "RÉPARATION BARRE ACKERMAN" },
  "Reposición caballitos sobredentadura": { en: "Overdenture clips replacement", fr: "Remplacement cavaliers overdenture" },
  "Reposición de Braquets autoligables (unidad)": { en: "Self-ligating bracket replacement (unit)", fr: "Remplacement bracket auto-ligaturant (unité)" },
  "Reposición de Braquets metálicos (unidad)": { en: "Metal bracket replacement (unit)", fr: "Remplacement bracket métallique (unité)" },
  "Reposiciones de completas con caballito s/Ackerman": { en: "Complete denture replacements with clip on Ackerman", fr: "Remplacement prothèses complètes avec cavalier sur Ackerman" },
  "resto": { en: "remainder", fr: "reste" },
  "Rete": { en: "Retainer", fr: "Contention" },
  "RETENCION ORTODONCIA": { en: "ORTHODONTIC RETENTION", fr: "RÉTENTION ORTHODONTIQUE" },
  "Retenedor fijo": { en: "Fixed retainer", fr: "Contention fixe" },
  "Retenedor removible inferior": { en: "Lower removable retainer", fr: "Contention amovible inférieure" },
  "Retenedor removible superior": { en: "Upper removable retainer", fr: "Contention amovible supérieure" },
  "Revision Anual + OPG + Higiene": { en: "Annual check-up + OPG + Hygiene", fr: "Révision annuelle + OPG + Hygiène" },
  "Revisión periódica para férula Michigan": { en: "Periodic Michigan splint check-up", fr: "Révision périodique gouttière Michigan" },
  "SEDACION": { en: "SEDATION", fr: "SÉDATION" },
  "Sellado oclusal": { en: "Occlusal sealant", fr: "Scellement occlusal" },
  "simple": { en: "simple", fr: "simple" },
  "SISTEMA ALL ON FOUR": { en: "ALL ON FOUR SYSTEM", fr: "SYSTÈME ALL ON FOUR" },
  "SISTEMA ALL ON SIX": { en: "ALL ON SIX SYSTEM", fr: "SYSTÈME ALL ON SIX" },
  "SOBREDENTADURA": { en: "OVERDENTURE", fr: "OVERDENTURE" },
  "TAC 1 ARCADA": { en: "CT SCAN 1 ARCH", fr: "SCANNER 1 ARCADE" },
  "TAC 2 ARCADAS": { en: "CT SCAN 2 ARCHES", fr: "SCANNER 2 ARCADES" },
  "Toma de biopsia": { en: "Biopsy", fr: "Biopsie" },
  "Tornillo cicatrización (unidad)": { en: "Healing screw (unit)", fr: "Vis de cicatrisation (unité)" },
  "Trata": { en: "Treatment", fr: "Traitement" },
  "Tratam": { en: "Treatment", fr: "Traitement" },
  "Tratamie": { en: "Treatment", fr: "Traitement" },
  "Tratamiento": { en: "Treatment", fr: "Traitement" },
  "TRATAMIENTO  ANTIGUO": { en: "PREVIOUS TREATMENT", fr: "TRAITEMENT ANTÉRIEUR" },
  "Tratamiento con protector bucal (para el deporte)": { en: "Treatment with mouthguard (for sport)", fr: "Traitement avec protège-dents (sport)" },
  "TRATAMIENTO DENTAL SEGUN ALBARAN": { en: "DENTAL TREATMENT PER DELIVERY NOTE", fr: "TRAITEMENT DENTAIRE SELON BON DE LIVRAISON" },
  "TRATAMIENTO ORTODONCIA INVISIBLE A MEDIDA": { en: "CUSTOM INVISIBLE ORTHODONTIC TREATMENT", fr: "TRAITEMENT ORTHODONTIQUE INVISIBLE SUR MESURE" },
  "Tratamiento Ortodóncia Invisible Todo Incl.": { en: "Invisible orthodontic treatment all inclusive", fr: "Traitement orthodontique invisible tout compris" },
  "TRATAMIENTO ORTODONTICO INVISALIGN CON RETENEDORES": { en: "INVISALIGN ORTHODONTIC TREATMENT WITH RETAINERS", fr: "TRAITEMENT ORTHODONTIQUE INVISALIGN AVEC CONTENTIONS" },
  "Tratamiento periodontal I cuadrante": { en: "Periodontal treatment quadrant I", fr: "Traitement parodontal quadrant I" },
  "Tratamiento periodontal II cuadrante": { en: "Periodontal treatment quadrant II", fr: "Traitement parodontal quadrant II" },
  "Tratamiento Periodontal III cuadrante": { en: "Periodontal treatment quadrant III", fr: "Traitement parodontal quadrant III" },
  "TRATAMIENTO PERIODONTAL INFERIOR": { en: "LOWER PERIODONTAL TREATMENT", fr: "TRAITEMENT PARODONTAL INFÉRIEUR" },
  "Tratamiento periodontal IV cuadrante": { en: "Periodontal treatment quadrant IV", fr: "Traitement parodontal quadrant IV" },
  "TRATAMIENTO PERIODONTAL SUPERIOR": { en: "UPPER PERIODONTAL TREATMENT", fr: "TRAITEMENT PARODONTAL SUPÉRIEUR" },
  "URGENCIA": { en: "EMERGENCY", fr: "URGENCE" },
  "URGENCIA  - CEMENTACION -": { en: "EMERGENCY - CEMENTATION -", fr: "URGENCE - CIMENTATION -" },
  "URGENCIA CON APERTURA": { en: "EMERGENCY WITH OPENING", fr: "URGENCE AVEC OUVERTURE" },
  "Visita": { en: "Visit", fr: "Visite" },
  "Visita de Urgencia": { en: "Emergency visit", fr: "Visite d'urgence" },
  "Visita tratamiento": { en: "Treatment visit", fr: "Visite de traitement" },
};

// Normaliza un nombre para comparación: recorta, colapsa espacios múltiples y NFC
const normName = (s) => s.trim().replace(/\s+/g, " ").normalize("NFC");

// Función que traduce un nombre usando el diccionario
// Si no existe, devuelve el original en español
export const translateTreatment = (name, lang) => {
  if (lang === "es") return name;

  // Strip trailing tooth number (e.g. "Corona metal ceramica   34" → base="Corona metal ceramica", suffix="   34")
  const toothSuffix = name.match(/(\s{2,}\d{1,2})$/);
  const baseName = toothSuffix ? name.slice(0, -toothSuffix[0].length) : name;
  const suffix = toothSuffix ? toothSuffix[0] : "";

  const n = normName(baseName);
  // Buscar exacto primero (normalizado)
  const entry = TREATMENT_DICT[n];
  if (entry && entry[lang]) return entry[lang] + suffix;
  // Buscar contra todas las claves normalizadas, case-insensitive
  const nLower = n.toLowerCase();
  const key = Object.keys(TREATMENT_DICT).find(k => normName(k).toLowerCase() === nLower);
  if (key && TREATMENT_DICT[key][lang]) return TREATMENT_DICT[key][lang] + suffix;
  // Fallback: devolver original
  return name;
};